from lograder.process.cli_args import (
    CLIArgs,
    CLIFlag,
    CLIKVOption,
    CLIMultiOption,
    CLIOption,
    CLIPresenceFlag,
)
from lograder.process.executable import (
    ExecutableInput,
    ExecutableOptions,
    ExecutableOutput,
    InstallationError,
    TypedExecutable,
    register_typed_executable,
)
from lograder.process.registry import (
    CMakeBuildArgs,
    CMakeConfigureArgs,
    CMakeExecutable,
    CURLArgs,
    CURLExecutable,
    GCCArgs,
    GCCExecutable,
    GXXArgs,
    GXXExecutable,
    MakefileArgs,
    MakefileExecutable,
)

__all__ = [
    "ExecutableInput",
    "ExecutableOutput",
    "ExecutableOptions",
    "TypedExecutable",
    "register_typed_executable",
    "CLIArgs",
    "CLIPresenceFlag",
    "CLIFlag",
    "CLIOption",
    "CLIMultiOption",
    "CLIKVOption",
    "CMakeConfigureArgs",
    "CMakeBuildArgs",
    "CMakeExecutable",
    "MakefileArgs",
    "MakefileExecutable",
    "GCCArgs",
    "GCCExecutable",
    "GXXArgs",
    "GXXExecutable",
    "CURLArgs",
    "CURLExecutable",
    "InstallationError",
]
